Repository gipplab/cs-insights-frontend, pull requests merged in 2022-07, with the labels that each got.

#39 Add more dashboards
  .env.development
  README.md
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/FilterAutocomplete.tsx
  src/components/FilterLabel.tsx
  src/components/FilterRange.tsx
  src/components/FilterTextfield.tsx
  src/components/Frame.tsx
  src/components/FrameWithGraphs.tsx
  src/components/IconLabel.tsx
  src/components/LoadingCircle.tsx
  src/components/ResponsiveAppBar.tsx
  src/components/Sidebar.tsx
  src/components/Tools.tsx
  src/components/charts/BarChart.tsx
  src/components/charts/BoxPlot.tsx
  src/components/charts/Grid.tsx
  src/components/charts/TreeMap.tsx
  src/consts.ts
  src/context/FilterContext.tsx
  src/context/RefreshContext.tsx
  src/network.tsx
  src/routes/authors.tsx
  src/routes/dashboards/authors.tsx
  src/routes/dashboards/citations.tsx
  src/routes/dashboards/fieldsOfStudy.tsx
  src/routes/dashboards/papers.tsx
  src/routes/dashboards/publishers.tsx
  src/routes/dashboards/topics.tsx
  src/routes/dashboards/typesOfPaper.tsx
  src/routes/dashboards/venues.tsx
  src/routes/home.tsx
  src/routes/papers.tsx
  src/routes/venues.tsx
  src/types.ts
Labels: Minor

#45 feat(Workflows): Add pipelines for PR and deploy #minor
  .github/workflows/deploy.yaml
  .github/workflows/main.yml
  .github/workflows/release.yml
  README.md
Labels: feature

#46 revert(Remove firebase): Firebase deploys are no longer necessary as …
  .firebaserc
  firebase.json
Labels: fix

#48 fix(Deploy): Dockerfile needs to build production code to be served
  .eslintrc
  Dockerfile
  package-lock.json
  package.json
Labels: fix

#54 feat(Deploy): Make frontend and backend talk with nginx and docker #m…
  .env.old
  .env.production
  Dockerfile
  nginx.conf
Labels: feature

#57 fix(Deploy): Change production env to relative path in host
  .env.production
Labels: fix

#58 fix(Deploy): Set frontend production ip in production build
  .env.production
Labels: fix

#59 Add http
  .env.production
Labels: fix

#71 Update main.yml
  .github/workflows/main.yml
Labels: test
