Repository gipplab/cs-insights-frontend, pull requests merged in 2022-08, with the labels that each got.

#75 Add lda topics dashboard
  .env.development
  .eslintrc
  .github/workflows/main.yml
  .github/workflows/release.yml
  CITATION.bib
  LICENSE
  README.md
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/ChartLoadingIcon.tsx
  src/components/FilterAutocomplete.tsx
  src/components/FilterLabel.tsx
  src/components/FilterRange.tsx
  src/components/Frame.tsx
  src/components/FrameWithGraphs.tsx
  src/components/IconLabel.tsx
  src/components/ModelIdAutocomplete.tsx
  src/components/ResponsiveAppBar.tsx
  src/components/Sidebar.tsx
  src/components/Tools.tsx
  src/components/charts/BoxPlot.tsx
  src/components/ldavis/index.js
  src/components/ldavis/ldavis.js
  src/components/ldavis/styles.module.css
  src/components/visualizations/BarChart.tsx
  src/components/visualizations/BoxPlot.tsx
  src/components/visualizations/Grid.tsx
  src/components/visualizations/LdaTopicVis.tsx
  src/components/visualizations/TreeMap.tsx
  src/consts.ts
  src/context/AuthContext.tsx
  src/context/ErrorBoundary.tsx
  src/context/FilterContext.tsx
  src/context/ModelIdContext.tsx
  src/context/RefreshContext.tsx
  src/context/SnackbarContext.tsx
  src/network.tsx
  src/routes/dashboards/authors.tsx
  src/routes/dashboards/citations.tsx
  src/routes/dashboards/fieldsOfStudy.tsx
  src/routes/dashboards/papers.tsx
  src/routes/dashboards/publishers.tsx
  src/routes/dashboards/topics.tsx
  src/routes/dashboards/typesOfPaper.tsx
  src/routes/dashboards/venues.tsx
  src/routes/home.tsx
  src/routes/login.tsx
  src/routes/register.tsx
  src/tools.ts
  src/types.ts
Labels: feature

#77 Treemap font size
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/main.yml
  .github/workflows/release.yml
  Dockerfile
  Dockerfile.development
  README.md
  package-lock.json
  package.json
  src/App.css
  src/components/ldavis/ldavis.js
  src/components/visualizations/TreeMap.tsx
  src/routes/home.tsx
  src/routes/login.tsx
  src/types.ts
Labels: fix

#79 Add two boxplots to citations dashboard
  src/App.css
  src/components/FrameWithGraphs.tsx
  src/components/visualizations/BarChart.tsx
  src/components/visualizations/BoxPlot.tsx
  src/components/visualizations/TreeMap.tsx
  src/routes/dashboards/authors.tsx
  src/routes/dashboards/citations.tsx
  src/routes/dashboards/fieldsOfStudy.tsx
  src/routes/dashboards/papers.tsx
  src/routes/dashboards/publishers.tsx
  src/routes/dashboards/typesOfPaper.tsx
  src/routes/dashboards/venues.tsx
  src/tools.ts
  src/types.ts
Labels: enhancement

#83 Fix height on topics dashboard
  src/components/visualizations/LdaTopicVis.tsx
  src/routes/home.tsx
Labels: fix

#90 Add open access as default filter
  src/context/FilterContext.tsx
Labels: fix

#93 ↪ New pull request labels for release changelog
  .github/workflows/release.yml
  pr_config.json
Labels: documentation

#95 🔑 Add https and ssl (also remove nginx from docker and start on host …
  Dockerfile
  nginx.conf
Labels: enhancement
